# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Alleg
version:      1.003
version_from: 
installdirs:  site
requires:
    Clone:                         0
    Data::Dumper:                  0
    enum:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
