package Alleg::Defaults;

use strict;
use Carp;

use Alleg::Util;

use vars qw($VERSION);

{
    local $^W;
    $VERSION = do { my @r = (q$Name: RELEASE_1_3 $ =~ /\d+/g); sprintf '%d.%03d'.'%02d' x ($#r-1), @r};
}

%Alleg::Chaff::DEFAULTS = (
    ac              => 11,
    build_type      => 0,
    cost            => 0,
    description     => "DEFAULT 'description'",
    group           => 0,
    hitpoints       => 35,
    icon            => "fxmine",
    life_span       => 2,
    load_time       => 3,
    mass            => 0.25,
    model           => "acs40",
    name            => "DEFAULT 'name'",
    pad0            => "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
    pad1            => "\xCC\xCC",
    pad3            => "\xCC",
    pad4            => "\xCD\xCD",
    pad5            => "\xCD",
    pad6            => "\xCD",
    pc_alpha        => 0,
    pc_blue         => 0,
    pc_green        => 0,
    pc_red          => 0,
    radius          => 5,
    rate_rotation   => 90,
    sig             => 1,
    sig_mod         => 0,
    stats_ss1       => 1,
    stats_ss2       => 0,
    strength        => undef,   # 1.5,
    techtree        => CORE::pack('a100'),
    type            => "part",
    uid             => undef,
    ukbmp           => "missle",
    use_mask        => undef, # 1,
    zero            => 0,
);

%Alleg::Drone::DEFAULTS = (
    ai_script        => undef, # 6,
    cost             => 1,
    description      => "DEFAULT 'description'",
    f1               => 0.5,
    f2               => 0.5,
    f3               => 0.5,
    group            => 0,
    model            => undef, # "utl14a",
    name             => "DEFAULT 'name'",
    null_string      => "\x00\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC",
    pad1             => "\xCC",
    pad2             => "\xCD\xCD",
    pad3             => "\xCD",
    part_uid         => -1,
    research_time    => 1,
    ship_uid         => undef,
    uid              => undef,
    zero             => 0,
);

%Alleg::Faction::DEFAULTS = (
    end              => "\xCD\xCD",
    factor_01        => undef,  #1,
    factor_02        => undef,  # 1,
    factor_03        => undef,  # 1,
    factor_04        => undef,  # 1,
    factor_05        => undef,  # 1,
    factor_06        => undef,  # 1,
    factor_07        => undef,  # 1,
    factor_08        => undef,  # 1,
    factor_09        => undef,  # 1,
    factor_10        => undef,  # 1,
    factor_11        => undef,  # 1,
    factor_12        => undef,  # 1,
    factor_13        => undef,  # 1,
    factor_14        => undef,  # 1,
    factor_15        => undef,  # 1,
    factor_16        => undef,  # 1,
    factor_17        => 1,
    factor_18        => undef,  # 1,
    factor_19        => undef,  # 1,
    factor_20        => undef,  # 1,
    factor_21        => 1,
    factor_22        => undef,  # 1,
    factor_23        => undef,  # 1,
    factor_24        => undef,  # 1,
    factor_25        => undef,  # 1,
    gar_uid          => undef,  # 15,
    model            => undef,  # "crimson",
    name             => "DEFAULT 'name'",
    obj              => "dialog",
    suk              => undef,  # 244,
    techtree_post    => undef,
    uid              => undef,  # 18,
    ukf1             => undef,  # 0,
    ukf2             => undef,  # 0,
);

%Alleg::Mine::DEFAULTS = (
    ac              => 11,
    cargo_payload   => undef,   # 2,
    cost            => 0,
    damage          => undef,   # 400,
    description     => "DEFAULT 'description'",
    dm              => 16,
    duration        => undef,   # 15,
    group           => 0,
    hitpoints       => 25,
    icon            => "fxmine",
    icon_bmp        => "minefield",
    load_time       => 2,
    mass            => 3,
    model           => "acs41",
    name            => "DEFAULT 'name'",
    pad0            => "\xCC\xCC\xCC\xCC",
    pad1            => "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
    pad2            => "\xCC\xCC",
    pad3            => "\x00\x00\x00\x00",
    pad4            => "\xCC",
    pad5            => "\xCD\xCD",
    pad6            => "\xCD",
    pad7            => "\xCD",
    pad8            => "\xCD\xCD\xCD",
    pad_zero        => 0,
    pc_alpha        => 0,
    pc_blue         => 0,
    pc_green        => 0,
    pc_red          => 0,
    radius          => undef,   # 100,
    rate_rotation   => 20,
    ship_sig        => 0,
    sig             => 0.150000005960464,
    stats_s7        => undef,   # 2000,
    techtree        => CORE::pack('a100'),
    type            => "part",
    uid             => undef,   # 11,
    usemask         => undef,   # 1,
    zero            => 0,
);

%Alleg::Missile::DEFAULTS = (
    dm              => undef,   # 4,
    ac              => 11,
    accel           => undef,   # 100,
    cargo_payload   => undef,   # 5,
    cm_resistance   => undef,   # 3,
    cost            => 0,
    damage          => undef,   # 100,
    damage_radius   => 0,
    description     => "DEFAULT 'description'",
    end             => "\xCD\xCD",
    group           => 0,
    header          => "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
    hitpoints       => undef,   # 20,
    icon            => "missle",
    launch_velocity => undef,   # 25,
    ldbmp           => undef,   # "mis05",
    life_span       => undef,   # 4,
    lock_radius     => undef,   # 0,
    lock_time       => undef,   # 0,
    mass            => undef,   # 1,
    max_lock        => undef,   # 0,
    model           => undef,   # "mis05",
    name            => "DEFAULT 'name'",
    pad0            => "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
    pad1            => "\xCC\xCC",
    pad2            => 0,
    pad3            => "\xCC",
    pad4            => "\xCD\xCD",
    pad5            => "\xCD",
    pad6            => "\xCD",
    rate_rotation   => undef,   # 50,
    ready_time      => 0.25,
    reload_time     => undef,   # 2,
    salvo_ratio     => undef,   # 0.050000000745058,
    scale           => undef,   # 2,
    sig             => 1,
    sig_mod         => undef,   # 0.25,
    sound_flight    => 540,
    sound_launch    => 500,
    special_effect  => undef,   # 0,
    stats_unused1   => 0,
    stats_unused2   => 0,
    techtree        => CORE::pack('a100'),
    turn_radius     => undef,   # 0.610865235328674,
    type            => "part",
    uid             => undef,   # 32,
    use_flags       => undef,   # 128,
    zero            => 0,
);

%Alleg::Part::Special::DEFAULTS = (
    overriding_uid   => 65535,
    pad3             => "\xCC",
    slot             => "invsmissile",
    suk2             => 10,
#    type             => 1,
#    uid              => 152,
#    usemask          => 34,
);

%Alleg::Part::DEFAULTS = (
    description         => "DEFAULT 'description'",
    group               => 0,
    header              => "\x00\x00\x00\x00\x00\x00\x00\x00",
    icon                => "part",
    model               => undef,   # "acs57",
    name                => "DEFAULT 'name'",
    overriding_uid      => 65535,
    pad1                => "\xCC",
    pad2                => "\xCC\xCC",
    pad3                => "\xCC",
    pad4                => "\xCC\xCC",
    slot                => "invdefault",
    stats_s1            => 1,
    suk1                => 0,
    suk2                => 16384,
    techtree            => CORE::pack('a100'),
    type                => 1,
    uid                 => undef,   # 52,
    usemask             => undef,   # 1,
);

%Alleg::Part::Booster::DEFAULTS = (%Alleg::Part::DEFAULTS,
    # Overrides from parent
    slot                 => "invafterburn",
    model                => "acs48",

    TODO                 => "",
    acceleration         => 0.5,
    activate_sound       => 680,
    consumption          => 0.000888800015673,
    deactivate_sound     => 700,
    thrust               => 1125,
    release_duration     => 2,
);

%Alleg::Part::Cloak::DEFAULTS = (%Alleg::Part::DEFAULTS,
    # Overrides from parent
    slot                 => "invcloak",
    model                => "acs38",

    energy_drain         => 120,
    sig_reduction        => 0.774999976158142,
    activation_duration  => 0.25,
    release_duration     => 0.25,
    activate_sound       => 640,
    deactivate_sound     => 660,
);

%Alleg::Part::Pack::DEFAULTS = (%Alleg::Part::DEFAULTS,
    # Overrides from parent
    slot             => "invdefault",
    model            => "acs29",
    TODO             => "",
    pack_type        => 0,
    pak_pad1         => 204,
    quantity         => 1000,
);

%Alleg::Part::Shield::DEFAULTS = (%Alleg::Part::DEFAULTS,
    # Overrides from parent
    slot                 => "invshield",
    model                => "acs30",

    TODO                 => "\xCC",
    recharge_rate        => 3.75,
    hitpoints            => 225,
    ac_type              => 8,
    activate_sound       => 580,
    shld_pad             => 204,
    shld_pad1            => 204,
    deactivate_sound     => 620,
);

%Alleg::Part::Weapon::DEFAULTS = (%Alleg::Part::DEFAULTS,
    # Overrides from parent
    slot                => "invsweapon",
    model               => "acs57",

    TODO                => "",
    activation_sound    => 92,
    ammo_consumption    => 0,
    burst_sound         => 52,
    energy_consumption  => 20,
    particle_spread     => 0,
    shot_interval       => 0.166999995708466,
    shot_sound          => 12,
    time_ready          => 0.25,
    wep_pad1            => "\xCC\xCC",
    wep_projectile_uid  => 36,
);

%Alleg::Probe::DEFAULTS = (
    TODO1                => "\x00\x00\x00\x00",
    TODO2                => "\x00\x00\x00\x00",
    accuracy             => 0.009999999776483,
    activation_delay     => "-1",
    ammo_capacity        => undef,  # 0,
    arming_time          => undef,  # 2,
    cargo_payload        => undef,  # 2,
    cost                 => undef,  # 0,
    description          => "DEFAULT 'description'",
    features             => undef,  # 0,
    group                => 0,
    hitpoints            => undef,  # 25,
    icon                 => "probe",
    leading              => undef,  # 0.75,
    lifespan             => undef,  # 3600,
    loadout_model        => undef,  # "utl23",
    mass                 => undef,  # 1,
    model                => undef,  # "utl23",
    model1               => "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
    name                 => "DEFAULT 'name'",
    pad1                 => "\xCC\xCC",
    pad2                 => "\xCC",
    pad3                 => "\xCD\xCD",
    pad4                 => "\x0B\xCD",
    pad5                 => "\xCD",
    pad6                 => "\xCD\xCD",
    pc_alpha            => 0,
    pc_blue             => 0,
    pc_green            => 0,
    pc_red              => 0,
    projectile           => undef,  # "-1",
    rate_rotation        => undef,  # 90,
    scale                => undef,  # 6,
    scan_range           => undef,  # 500,
    shot_interval        => undef,  # 0.200000002980232,
    sig                  => undef,  # 0.300000011920929,
    sound                => 720,
    type                 => "part",
    uid                  => undef,  # 22,
    usemask              => undef,  # 1,
    zero                 => 0,
);

%Alleg::Projectile::DEFAULTS = (
    dm                  => undef,  # 16,
    absolute_speed      => 1,
    ambient_sound       => 65535,
    area_dmg_per_shot   => undef,  # 0,
    area_dmg_radius     => undef,  # 0,
    directional         => 0,      # 1,
    file_model          => "",
    file_texture        => undef,  # "fx95",
    lifespan            => undef,  # 2,
    pad2                => "\xCC\xCC",
    pad3                => "\xCC\xCC\xCC",
    pad4                => "\xCC\xCC",
    particle_size       => 2,
    pc_alpha            => 0,
    pc_blue             => 0,
    pc_green            => 0,
    pc_red              => 0,
    rate_rotation       => undef,  # 0,
    reg_dmg_per_shot    => undef,  # 10,
    speed               => undef,  # 500,
    uid                 => undef,  # 32,
    width_over_height   => undef,  # 0.100000001490116,
);

%Alleg::Research::DEFAULTS = (
    cat              => undef,  # 940,
    cost             => 1,
    description      => "DEFAULT 'description'",
    factor_01        => 1,
    factor_02        => 1,
    factor_03        => 1,
    factor_04        => 1,
    factor_05        => 1,
    factor_06        => 1,
    factor_07        => 1,
    factor_08        => 1,
    factor_09        => 1,
    factor_10        => 1,
    factor_11        => 1,
    factor_12        => 1,
    factor_13        => 1,
    factor_14        => 1,
    factor_15        => 1,
    factor_16        => 1,
    factor_17        => 1,
    factor_18        => 1,
    factor_19        => 1,
    factor_20        => 1,
    factor_21        => 1,
    factor_22        => 1,
    factor_23        => 1,
    factor_24        => 1,
    factor_25        => 1,
    icon             => "icontech",
    model            => undef,  # "genericres01",
    name             => "DEFAULT 'name'",
    pad1             => 0,
    pad2             => "\xCD\xCD",
    research_time    => 120,
    root_tree        => undef,  # 1,
    uid              => undef,  # 56,
    uk1              => 204,
);

%Alleg::Ship::DEFAULTS = (
    ac                      => undef,  # 1,
    drift_pitch             => undef,  # 175.532928466797,
    drift_roll              => undef,  # 174.532928466797,
    drift_yaw               => undef,  # 174.532928466797,
    max_pitch_rate          => undef,  # 0.872664630413055,
    max_roll_rate           => undef,  # 0.872664630413055,
    max_yaw_rate            => undef,  # 0.872664630413055,
    rtm                     => undef,  # 0.25,
    stm                     => undef,  # 0.5,
    sound_exterior          => 200,    # 180,
    sound_interior          => 160,    # 140,
    sound_thrust_exterior   => 280,    # 260,
    sound_thrust_interior   => 240,    # 220,
    sound_turn_exterior     => 360,    # 340,
    sound_turn_interior     => 320,    # 300,
    ammo_capacity           => undef,  # 800,
    can_use_01              => undef,  # 0,
    can_use_02              => undef,  # 0,
    can_use_03              => undef,  # 0,
    can_use_04              => undef,  # 0,
    can_use_05              => undef,  # 0,
    can_use_06              => undef,  # 0,
    can_use_07              => undef,  # 0,
    can_use_08              => undef,  # 0,
    cm_capacity             => undef,  # 5,
    cost                    => 0,
    def_loadout_01          => 65535,
    def_loadout_02          => 65535,
    def_loadout_03          => 65535,
    def_loadout_04          => 65535,
    def_loadout_05          => 65535,
    def_loadout_06          => 65535,
    def_loadout_07          => 65535,
    def_loadout_08          => 65535,
    def_loadout_09          => 65535,
    def_loadout_10          => 65535,
    def_loadout_11          => 65535,
    def_loadout_12          => 65535,
    def_loadout_13          => 65535,
    def_loadout_14          => 65535,
    description             => "DEFAULT 'description'",
#    zero                    => undef,
    group                   => undef,
    energy                  => undef,   # 1500,
    fuel                    => undef,   # 5,
    hullability             => undef,   # 146,
    icon                    => undef,   # "scout",
    lock_mode               => undef,   # 1,
    mass                    => undef,   # 40,
    max_thrust              => undef,   # 1200,
    missiles_capacity       => undef,   # 15,
    mnt_nbwpslots           => 0,       # 1,
    model                   => undef,   # "fig05",
    name                    => "DEFAULT 'name'",
    nb_parts                => 0,       # 0,
    overriding_uid          => 65535,
    pack_capacity           => undef,   # 2,
    recharge                => undef,   # 60,
    rip_cost                => undef,   # 1000,
    rip_time                => undef,   # 10,
    scale                   => undef,   # 11.3999996185303,
    scan                    => undef,   # 3000,
    sig                     => undef,   # 0.5,
    speed                   => undef,   # 180,
    stats_hp                => undef,   # 225,
    techtree                => CORE::pack('a100'),
    uid                     => undef,   # 263,

    # Misc/unknown/junk
    header  => CORE::pack('a4'),
    TODO2   => "\x1C\x02",
    TODO3   => CORE::pack('a14'),
    TODO4   => CORE::pack('a2'),
    pad1    => CORE::pack('a'),
    pad2    => CORE::pack('a2'),
);

%Alleg::Ship::PART_DEFAULTS = (
    uk1         => 140,
    uk2         => 121,
    position    => "wepemt",
    todo        => "0\x00\x00\x00\x00\x00\x00\x00\x00", # CORE::pack('a9'),
    part_mask   => 0,
    part_type   => 1,
);

%Alleg::Station::DEFAULTS = (
    ac_hull         => undef,  # 12,
    ac_shield       => undef,  # 13,
    ability_bitmask => undef,  # 375,
    techtree_local  => undef,  # "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
    buildon         => undef,  # 8,
    constructor     => "DEFAULT 'constructor'",
    cost            => 1,
    description     => "DEFAULT 'description'",
    group           => 0,
    hull            => undef,  # 6666,
    hull_repair     => undef,  # 15,
    icon            => undef,  # "station",
    model           => undef,  # "ss92",
    name            => "DEFAULT 'name'",
    overriding_uid  => 65535,
    pad1            => "\x00",
    pad2            => "\xCD\xCD",
    pad6            => 205,
    research_time   => 120,
    scale           => undef,  # 302.5,
    scan_range      => undef,  # 2400,
    sheild_repair   => undef,  # 30,
    shield          => undef,  # 6666,
    sig             => undef,  # 1,
    sound_01        => undef,  # 741,
    sound_02        => undef,  # 761,
    sound_03        => undef,  # 781,
    sound_04        => undef,  # 801,
    sound_05        => undef,  # 420,
    sound_06        => undef,  # 380,
    sound_07        => undef,  # 460,
    sound_08        => undef,  # 821,
    sound_09        => undef,  # 841,
    sound_10        => undef,  # 861,
    sound_11        => undef,  # 881,
    sound_12        => undef,  # 921,
    sound_13        => undef,  # 901,
    stats_income    => undef,  # 0,
    stats_ss0       => undef,  # 27,
    type            => undef,  # 1,
    uid             => undef,  # 2,
    uk3             => "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
    zero            => 0,
);

1;
__END__
